#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        echo "This script must run as root (or with sudo)." >&2
        exit 1
    fi
}

has_cmd() {
    command -v "$1" >/dev/null 2>&1
}

detect_pm() {
    if has_cmd apt-get; then
        echo "apt"
        return
    fi
    if has_cmd dnf; then
        echo "dnf"
        return
    fi
    if has_cmd yum; then
        echo "yum"
        return
    fi
    echo "unsupported"
}

ensure_docker() {
    local pm
    pm="$(detect_pm)"

    if has_cmd docker && docker info >/dev/null 2>&1; then
        return
    fi

    echo "Docker is missing or daemon is not active. Installing..."
    case "$pm" in
        apt)
            apt-get update
            apt-get install -y docker.io docker-compose-plugin
            systemctl enable --now docker || true
            ;;
        dnf)
            dnf install -y docker docker-compose-plugin
            systemctl enable --now docker || true
            ;;
        yum)
            yum install -y docker docker-compose-plugin
            systemctl enable --now docker || true
            ;;
        *)
            echo "Unsupported package manager. Install Docker manually first." >&2
            exit 1
            ;;
    esac
}

ensure_compose() {
    if docker compose version >/dev/null 2>&1; then
        return
    fi

    echo "Docker Compose plugin is missing. Installing..."
    case "$(detect_pm)" in
        apt) apt-get update && apt-get install -y docker-compose-plugin ;;
        dnf) dnf install -y docker-compose-plugin ;;
        yum) yum install -y docker-compose-plugin ;;
        *)
            echo "Unsupported package manager. Install docker compose plugin manually." >&2
            exit 1
            ;;
    esac
}

clamp_int() {
    local value="$1" min="$2" max="$3"
    if [ "$value" -lt "$min" ]; then
        echo "$min"
    elif [ "$value" -gt "$max" ]; then
        echo "$max"
    else
        echo "$value"
    fi
}

pick_resolution() {
    local cpus="$1" mem_gb="$2"
    if [ "$cpus" -ge 8 ] && [ "$mem_gb" -ge 16 ]; then
        echo "1920x1080"
    elif [ "$cpus" -ge 4 ] && [ "$mem_gb" -ge 8 ]; then
        echo "1600x900"
    else
        echo "1366x768"
    fi
}

pick_profile_name() {
    local cpus="$1" mem_gb="$2"
    if [ "$cpus" -ge 12 ] && [ "$mem_gb" -ge 24 ]; then
        echo "large"
    elif [ "$cpus" -ge 8 ] && [ "$mem_gb" -ge 16 ]; then
        echo "medium"
    elif [ "$mem_gb" -le 3 ]; then
        echo "tiny"
    else
        echo "small"
    fi
}

compute_env() {
    local host_cpus mem_total_kb mem_total_gb
    local tuned_cpus tuned_mem_gb tuned_shm_gb
    local ff_proc ff_webiso ff_cache_kb
    local vnc_resolution profile_name

    host_cpus="$(nproc)"
    mem_total_kb="$(awk '/MemTotal:/ {print $2}' /proc/meminfo)"
    mem_total_gb=$(( mem_total_kb / 1024 / 1024 ))

    tuned_cpus=$(( host_cpus - 1 ))
    tuned_cpus="$(clamp_int "$tuned_cpus" 2 12)"

    tuned_mem_gb=$(( mem_total_gb * 60 / 100 ))
    tuned_mem_gb="$(clamp_int "$tuned_mem_gb" 2 24)"

    tuned_shm_gb=$(( tuned_mem_gb / 4 ))
    tuned_shm_gb="$(clamp_int "$tuned_shm_gb" 1 8)"

    # Firefox process tuning — 小规格机器更激进
    if [ "$tuned_mem_gb" -le 4 ]; then
        ff_proc=1
        ff_webiso=1
        ff_cache_kb=32768
    elif [ "$tuned_mem_gb" -le 8 ]; then
        ff_proc=2
        ff_webiso=1
        ff_cache_kb=65536
    else
        ff_proc=$(( tuned_cpus / 2 ))
        ff_proc="$(clamp_int "$ff_proc" 2 8)"
        ff_webiso=$(( ff_proc / 2 ))
        ff_webiso="$(clamp_int "$ff_webiso" 1 4)"
        ff_cache_kb=$(( tuned_mem_gb * 1024 * 1024 / 16 ))
        ff_cache_kb="$(clamp_int "$ff_cache_kb" 65536 524288)"
    fi

    vnc_resolution="$(pick_resolution "$tuned_cpus" "$tuned_mem_gb")"
    profile_name="$(pick_profile_name "$tuned_cpus" "$tuned_mem_gb")"

    cat > "$ENV_FILE" <<EOF
# Auto-generated by autotune-deploy.sh
OPENCLAW_PROFILE=${profile_name}
OPENCLAW_CONTAINER_NAME=openclaw-desktop
OPENCLAW_VNC_PORT=5901
OPENCLAW_NOVNC_PORT=6080
OPENCLAW_GATEWAY_PORT=18789
OPENCLAW_VNC_PASSWORD=openclaw
OPENCLAW_VNC_RESOLUTION=${vnc_resolution}
OPENCLAW_VNC_DEPTH=24
OPENCLAW_CPUS=${tuned_cpus}
OPENCLAW_MEM_LIMIT=${tuned_mem_gb}g
OPENCLAW_SHM_SIZE=${tuned_shm_gb}g
OPENCLAW_FIREFOX_PROCESS_COUNT=${ff_proc}
OPENCLAW_FIREFOX_WEB_ISOLATED_COUNT=${ff_webiso}
OPENCLAW_FIREFOX_CACHE_MEMORY_KB=${ff_cache_kb}
EOF

    echo "Auto tune result:"
    echo "  Host: ${host_cpus} CPU / ${mem_total_gb}GiB RAM"
    echo "  Profile: ${profile_name}"
    echo "  Container CPU: ${tuned_cpus}"
    echo "  Container MEM: ${tuned_mem_gb}GiB"
    echo "  Container SHM: ${tuned_shm_gb}GiB"
    echo "  VNC Resolution: ${vnc_resolution}"
    echo "  Firefox processCount: ${ff_proc} (webIsolated=${ff_webiso})"
    echo "  Env file: ${ENV_FILE}"
}

deploy_or_update() {
    local container_name
    local first_install
    container_name="${OPENCLAW_CONTAINER_NAME:-openclaw-desktop}"

    if docker ps -a --format '{{.Names}}' | grep -qx "${container_name}"; then
        first_install="no"
    else
        first_install="yes"
    fi

    if [ "$first_install" = "yes" ]; then
        echo "Detected first installation. Building and starting container..."
    else
        echo "Detected existing installation. Rebuilding and rolling update..."
    fi

    docker compose -f "${ROOT_DIR}/docker-compose.yml" --env-file "$ENV_FILE" up -d --build
}

main() {
    require_root
    ensure_docker
    ensure_compose
    compute_env
    deploy_or_update
    echo "Done."
}

main "$@"
